### ISSUE TITLE
v1.1 Roadmap

### ISSUE THREAD

**Issue by Kevadroz** [HelldogPack/JoyMix-modpack#1]
- [x] Registrar materiales de Silent Gear.
- [x] ~~Crear contenido de Bountiful.~~
- [x] Añadir recursos faltantes (panorama).
- [x] Configuraciones y contenido miscelaneos.
